name: My Workflow

on:
  push:  # will run on any push

jobs:
  prepare:
    uses: niqzart/ca-actions/.github/workflows/full-workflow.yml@v1.0
    with:
      python_version: 3.9
      pytest_workdir: test
      coverage_path: ../machine
      mypy: false
      flake8: false
      black: false
      isort: false
      
