name: My Workflow

on:
  push:  # will run on any push

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip

      - id: install
        name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run pytest
        run: >
          pytest
          .
          -p no:cacheprovider

      - name: Run pytest with coverage
        run: pytest . -p no:cacheprovider --cov=./machine --cov-fail-under=0

      - name: Report test coverage
        run: >
          coverage
          report